# Use the official Python image as base
FROM python:3.12-alpine

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set the working directory in the container
WORKDIR /app

# Copy the requirements file into the container
COPY req.txt /app/

# Install dependencies, including GDAL
RUN pip install --no-cache-dir -r req.txt

# Copy the project files into the container
COPY . /app/

# Expose port 8000 to the outside world
EXPOSE 8000

RUN python manage.py collectstatic --noinput
# Run migrations and start the server
CMD ["sh", "-c", "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"]
